---
# update Shippable resource state with this job number
- name: run cmd
  shell: |
    shipctl post_resource_state "{{ CLUSTER_RES_NAME }}" versionName "build-${BUILD_NUMBER}"

# provision ECS cluster
- name: Create ECS Cluster {{ ecs_cluster_name }}
  ecs_cluster:
    name: "{{ ecs_cluster_name }}"
    state: present
  register: ecs

# update shippable resource state with provisioned cluster_arn
- name: run cmd
  shell: |
    shipctl put_resource_state "{{ CLUSTER_RES_NAME }}" "CLUSTER_ARN" "{{ ecs.cluster.clusterArn }}"
    shipctl put_resource_state "{{ CLUSTER_RES_NAME }}" "region" "{{ ec2_region }}"
    shipctl put_resource_state "{{ CLUSTER_RES_NAME }}" "sourceName" "{{ ecs_cluster_name }}"
