---
# update Shippable resource state with this job number
- name: run cmd
  shell: |
    shipctl post_resource_state "{{ CLUSTER_RES_NAME }}" versionName "build-${BUILD_NUMBER}"

# Terminate ECS cluster
- name: Terminate ECS Cluster {{ ecs_cluster_name }}
  ecs_cluster:
    name: "{{ ecs_cluster_name }}"
    state: absent
  register: ecs

# update Shippable resource state with provisioned CLUSTER_ARN
- name: run cmd
  shell: |
    shipctl put_resource_state "{{ CLUSTER_RES_NAME }}" STATUS "empty"
